- name: Create sysvinit script
  template:
    src: Ubuntu.14.04/blynk.init.j2
    dest: /etc/init.d/blynk
    mode: 0755

- name: Create default for the init script
  template:
    src: Ubuntu.14.04/blynk.default.j2
    dest: /etc/default/blynk
    mode: 0644
  notify: Restart blynk
