---

- name: Create blynk group
  group:
    name: "{{ blynk_server_group }}"

- name: Create blynk user
  user:
    name: "{{ blynk_server_user }}"

- name: Create blynk home dir
  file:
    path: "{{ blynk_server_home }}"
    owner: "{{ blynk_server_user }}"
    group: "{{ blynk_server_group }}"
    state: directory
    mode: 0755

- name: Create config dir
  file:
    path: "{{ blynk_server_config_dir }}"
    state: directory

- name: Install libxrender
  yum:
    name: libXrender
    state: present

- name: Install OpenSSL
  yum:
    name: openssl
    state: present

- name: Install blynk server
  get_url:
    url: "{{ blynk_server_dist_url }}"
    dest: "{{ blynk_server_bin }}"
    mode: 0755
    checksum: "sha1:{{ blynk_server_version_checksum[blynk_server_version]['sha1'] }}"

- name: Create systemd unit file
  template:
    src: RedHat/blynk.service.j2
    mode: 0664
    dest: /etc/systemd/system/blynk.service

- name: Enable blynk on startup
  systemd:
    name: blynk
    daemon_reload: yes
    enabled: yes
