---

- name: Create blynk group
  group:
    name: "{{ blynk_server_group }}"

- name: Create blynk user
  user:
    name: "{{ blynk_server_user }}"

- name: Create blynk home dir
  file:
    path: "{{ blynk_server_home }}"
    owner: "{{ blynk_server_user }}"
    group: "{{ blynk_server_group }}"
    state: directory
    mode: 0755

- name: Create config dir
  file:
    path: "{{ blynk_server_config_dir }}"
    state: directory

- include: "init-{{ ansible_distribution }}.{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Install libxrender
  apt:
    name: libxrender1
    state: present

- name: Install blynk server
  get_url:
    url: "{{ blynk_server_dist_url }}"
    dest: "{{ blynk_server_bin }}"
    mode: 0755
    checksum: "sha1:{{ blynk_server_version_checksum[blynk_server_version]['sha1'] }}"
