---
# tasks file for ansible-role-blynk-server

- include_vars: "{{ ansible_os_family }}.yml"

- set_fact:
    blynk_server_config_merged: "{{ blynk_server_config_default | combine(blynk_server_config, recursive = True) }}"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create TLS cert
  template:
    src: tls_cert.j2 
    dest: "{{ blynk_server_config_merged['server.ssl.cert'] }}"
    mode: 0644
  notify: Restart blynk

- name: Create TLS key
  template:
    src: tls_key.j2 
    dest: "{{ blynk_server_config_merged['server.ssl.key'] }}"
    mode: 0640
    group: "{{ blynk_server_group }}"
  notify: Restart blynk

- name: Create log directory
  file:
    path: "{{ blynk_server_config_merged['logs.folder'] }}"
    mode: 0755
    owner: "{{ blynk_server_user }}"
    group: "{{ blynk_server_group }}"
    state: directory
  notify: Restart blynk

- name: Create db directory
  file:
    path: "{{ blynk_server_config_merged['data.folder'] }}"
    mode: 0755
    owner: "{{ blynk_server_user }}"
    group: "{{ blynk_server_group }}"
    state: directory
  notify: Restart blynk

- name: Create server.properties
  template:
    src: server.properties.j2
    dest: "{{ blynk_server_config_path }}"
  notify: Restart blynk

- name: Start blynk
  service:
    name: "{{ blynk_server_service }}"
    enabled: true
    state: started
  register: register_blynk_start

- name: Wait for blynk to start after `Start blynk`
  wait_for:
    host: 127.0.0.1
    port: "{{ blynk_server_config_merged['app.ssl.port'] }}"
  when:
    - register_blynk_start.changed
